### ISSUE TITLE
Question : Could we build HDMIsupply in flame2020?

### ISSUE THREAD

**Issue by runabird36** [lcrs/HDMIsupply#1]
Hi, 

Thanks for your shared 'HDMIsupply'.
we used it in flame2019 well. 

**By the way, we are wondering that could we use 'HDMIsupply' in flame2020 version.
Could we use it?**

Thanks for reading my words in busy time.
Have nice day!

**Comment by lcrs** [comment]
Yes - I've used it in 2020, and it should also work in 2021 for that matter - lmk if you try it and have problems :)

**Comment by runabird36** [comment]
we're happy to hear that.

we wil try with the released version

Thanks with your care
